apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: arm-exporter
  namespace: monitoring
  labels:
    k8s-app: arm-exporter
spec:
  selector:
    matchLabels:
      k8s-app: arm-exporter
  template:
    metadata:
      name: arm-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '9243'
      labels:
        k8s-app: arm-exporter
    spec:
      hostNetwork: true
      containers:
      - image: carlosedp/arm_exporter
        name: arm-exporter
        ports:
        - name: http
          containerPort: 9243
          hostPort: 9243
