apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app: arm-exporter
    k8s-app: arm-exporter
  name: arm-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 9243
    protocol: TCP
  selector:
    k8s-app: arm-exporter

