---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-station-exporter
  labels:
    name: weather-station-exporter
  namespace: monitoring
data:
  config.yml: |-
    baseurl: "https://www.bogner-lehner.eu/lwd"
    timeout: 10
    sites:
    - arlingsattel
    - hengstpass
    - hieflerstutzen
    - kasberg

