apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    longterm: 'true'
  name: weather-station-exporter
  namespace: monitoring
spec:
  selector: 
    app: weather-station-exporter 
  ports:
    - port: 8080
      targetPort: 8080
