apiVersion: v1
kind: Service
metadata:
  name: alertmanager-external
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    nodePort: 30002
