apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: tnosaj/blackbox_exporter-arm:latest
        ports:
        - name: blackbox
          containerPort: 9115
        resources:                      
          limits:                     
            cpu: "1"                   
            memory: 64Mi     
          requests:            
            cpu: 200m        
            memory: 64Mi

