apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
   app: grafana
   prometheus: k8s
 name: grafana
 namespace: monitoring
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 512Mi
