apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  selector: 
    app: grafana
    component: core
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

