apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: core
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: grafana
    component: core
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

