---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: node-exporter
    k8s-app: node-exporter
  name: router-node-exporter
  namespace: monitoring
spec:
  selector:
    app: router-node-exporter
  ports:
  - name: http
    protocol: TCP
    port: 9100
    targetPort: 9100
  externalIPs:
  - 192.168.1.1
---
kind: Endpoints
apiVersion: v1
metadata:
  labels:
    app: node-exporter
    k8s-app: node-exporter
  name: router-node-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - name: http
        port: 9100
        protocol: TCP
