apiVersion: v1
kind: Endpoints
metadata:
  annotations:
  labels:
    app: node-exporter
    k8s-app: node-exporter
  name: router-node-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.1.1
  ports:
  - name: http
    port: 9101
    protocol: TCP

