{
 "title": "Hardware",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wrk-1",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.1.31:9243\"}"
    }
   ]
  },
  {
   "title": "wrk-2",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.1.32:9243\"}"
    }
   ]
  },
  {
   "title": "wrk-3",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.1.33:9243\"}"
    }
   ]
  },
  {
   "title": "wrk-4",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=\"192.168.1.34:9243\"}"
    }
   ]
  },
  {
   "title": "Core Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}