{
 "title": "Weather Stations",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": "label_values(weather_station_snow_hight,site)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_air_temperature{site='$site'}"
    }
   ]
  },
  {
   "title": "Current Snow Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "lengthm",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_snow_hight{site=\"$site\"}/100"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_air_humidity{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "velocitykmh",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_speed{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Gusts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "velocitykmh",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_gust_speed{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Direction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_direction{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Air Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "weather_station_air_humidity", "legendFormat": "{{ site }}" }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "weather_station_air_temperature",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Snow hight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "weather_station_air_temperature / 100",
     "legendFormat": "{{ site }}"
    },
    {}
   ]
  },
  {
   "title": "Surface Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "weather_station_surface_temperature",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Wind Speeds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    { "expr": "weather_station_wind_speed", "legendFormat": "{{ site }}" },
    {
     "expr": "weather_station_wind_gust_speed",
     "legendFormat": "{{ site }} - gusts"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    { "expr": "weather_station_wind_direction", "legendFormat": "{{ site }}" }
   ]
  }
 ]
}