apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 80s
      evaluation_interval: 75s
    rule_files:
      - /etc/config/*.rules
    alerting:
      alertmanagers:
      - scheme: http
        path_prefix: "alertmanager/"
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'fk-traun-node'
        metrics_path: '/node/metrics'
        static_configs:
          - targets: ['monitoring.freikirche-traun.at']
      - job_name: 'fk-traun-mysql'
        metrics_path: '/mysql/metrics'
        static_configs:
          - targets: ['monitoring.freikirche-traun.at']
      - job_name: 'fk-traun-nginx'
        metrics_path: '/nginx/metrics'
        static_configs:
          - targets: ['monitoring.freikirche-traun.at']
      - job_name: 'router'
        static_configs:
          - targets: ['192.168.1.1:9101']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://freikirche-traun.at
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter.monitoring.svc:9115
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: kubernetes_pod_node_name
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - job_name: 'kubernetes-ingresses'
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
        - role: ingress
        relabel_configs:
        - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
          regex: (.+);(.+);(.+)
          replacement: ${1}://${2}${3}
          target_label: __param_target
        - target_label: __address__
          replacement: blackbox-exporter.monitoring.svc:9115
        - source_labels: [__param_target]
          target_label: instance
        - action: labelmap
          regex: __meta_kubernetes_ingress_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_ingress_name]
          target_label: kubernetes_name
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name

  fk.rules: |-
    groups:
      - name: fk
        rules:
          - alert: nginxDown
            expr: nginx_up{instance="monitoring.freikirche-traun.at:80"} != 1
            for: 5m
            labels:
              severity: slack
              channel: '#alerts'
            annotations:
              title: "nginx is down"
              description: "@here - nginx exporter is not reporting, or is down. check it out."
          - alert: mysqlDown
            expr: mysql_up{instance="monitoring.freikirche-traun.at:80"} != 1
            for: 5m
            labels:
              severity: slack
              channel: '#alerts'
            annotations:
              title: "mysql is down"
              description: "@here - mysql exporter is not reporting, or is down. check it out."
          - alert: nodeDfLow
            expr: (((node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"} - node_filesystem_free_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) / node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) * 100 > 80 ) and (((node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"} - node_filesystem_free_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) / node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) * 100 < 90 ) 
            for: 5m
            labels:
              severity: slack
              channel: '#alerts'
            annotations:
              title: "Space is getting low"
              description: "@here - Disk free on {{ $labels.mountpoint }} is getting low: {{ $value }}. check it out."
          - alert: nodeDfCritical
            expr: ((node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"} - node_filesystem_free_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) / node_filesystem_size_bytes{instance="monitoring.freikirche-traun.at:80", device!="tmpfs"}) * 100 >= 90 
            for: 5m
            labels:
              severity: slack
              channel: '#alerts'
            annotations:
              title: "Space is getting critically low"
              description: "@here - Disk free on {{ $labels.mountpoint }} is getting low: {{ $value }}. check it out."
          - alert: nodeMem
            expr: ((node_memory_MemTotal_bytes{instance="monitoring.freikirche-traun.at:80"} - node_memory_MemFree_bytes{instance="monitoring.freikirche-traun.at:80"}  - node_memory_Buffers_bytes{instance="monitoring.freikirche-traun.at:80"} - node_memory_Cached_bytes{instance="monitoring.freikirche-traun.at:80"}) / node_memory_MemTotal_bytes{instance="monitoring.freikirche-traun.at:80"}) > 0.8
            for: 5m
            labels:
              severity: slack
              channel: '#alerts'
            annotations:
              title: "Free Memory is getting low."
              description: "@here - Free memory is low: {{ $value }}."
