apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  serviceName: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        kubernetes.io/hostname: wrk-3
      containers:
    spec:
      volumes:
       - name: config
         persistentVolumeClaim:
          claimName: homeassistant
       - name: dev-usb0
         hostPath:
           type: CharDevice
           path: /dev/ttyUSB0
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        imagePullPolicy: Always
        name: home-assistant
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 800m
            memory: 768Mi
        volumeMounts:
         - mountPath: "/config"
           name: config
         - mountPath: "/dev/ttyUSB0"
           name: dev-usb0
        securityContext:
          privileged: true
      restartPolicy: Always
