apiVersion: v1
kind: Service
metadata:
  name: homeassistant-ext
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  ports:
  - nodePort: 31123
    port: 8123
    protocol: TCP
  selector:
    app: homeassistant
  type: NodePort
