apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-exporter-config
  namespace: monitoring
data:
  config.yml: |-
    targets:
      - 8.8.8.8
      - 1.1.1.1
      - 192.168.0.1
    dns:
      refresh: 2m15s
      nameserver: 192.168.1.1
    ping:
      interval: 2s
      timeout: 3s
      history-size: 42
      payload-size: 120
      fw-mark: 222
    options:
      disableIPv6: true
