---
apiVersion: v1
kind: Service
metadata:
  name: ping-monitoring
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9427'
  labels:
    longterm: 'true'
spec:
  selector:
    app: ping-exporter
  ports:
  - port: 9427
    targetPort: 9427
