{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Home Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "hass_temperature_c", "legendFormat": "{{ friendly_name}}" }
   ]
  },
  {
   "title": "Snow Height",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    { "expr": "weather_station_snow_hight/100", "legendFormat": "{{ site }}" }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 } }
 ]
}
{
 "title": "Docker",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Running containers without \"pause\"",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"^/docker.*\",image!=\"gcr.io/google_containers/pause-amd64:3.0\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Grafana",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(grafana_info,kubernetes_name)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(grafana_info,version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{kubernetes_name=\"$pod\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "singlestat",
   "description": "total amount of orgs",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{kubernetes_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "singlestat",
   "description": "total amount of users",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_users{kubernetes_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    { "expr": "topk(1, grafana_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "singlestat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(grafana_alerting_active_alerts[1m])"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_name=\"$pod\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Response Statuses",
   "type": "graph",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp Details",
   "type": "graph",
   "description": "http request counter",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "graph",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_login_post_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "graph",
   "description": "summary for dataproxy request duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Avg [5 min]",
   "type": "graph",
   "description": "average dataproxy request duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "Average Requests Duration"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}
{
 "title": "Router",
 "description": "Host overview tuned to router specs",
 "tags": [
  "system",
  "os"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "router",
    "query": "label_values(node_openwrt_info,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Contract Table",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$router$\"}/node_nf_conntrack_entries_limit {instance=~\"$router$\"}*100"
    }
   ]
  },
  {
   "title": "Router CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{instance=~\"$router$\",mode!=\"idle\"})/sum(node_cpu_seconds_total{instance=~\"$router$\"})*100"
    }
   ]
  },
  {
   "title": "Router Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$router$\"}-node_memory_MemFree_bytes{instance=~\"$router$\"})/(node_memory_MemTotal_bytes{instance=~\"$router$\"}) * 100"
    }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "received",
     "expr": "rate(node_nat_traffic{dest!~\"192.168.1.*\",instance=~\"$router$\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{src}} - {{dest}}",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "br-wan" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(20, rate(node_nat_traffic{dest!~\"192.168.1.*\",instance=~\"$router$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Network Traffic (br-wan)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "received",
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$router$\"}[2m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "br-wan" }
     ]
    }
   ]
  },
  {
   "title": "Errors/Drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$router$\"}[2m])",
     "legendFormat": "{{device}} drops"
    },
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$router$\"}[2m])",
     "legendFormat": "{{device}} error"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$router$\"}[2m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "short",
     "expr": "node_load1{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "short",
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "medium",
     "expr": "node_load5{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "mid",
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "long",
     "expr": "node_load15{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "long",
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "alias": "used",
     "expr": "sum((node_memory_MemTotal_bytes{instance=~\"$router$\"}-node_memory_MemFree_bytes{instance=~\"$router$\"}-node_memory_Cached_bytes{instance=~\"$router$\"})/(node_memory_MemTotal_bytes{instance=~\"$router$\"})) by (job) * 100",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "%",
     "measurement": "memory_value",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"host\" =~ /^$host$/ AND \"type_instance\" = 'used' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Memory Distrubution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "free",
     "expr": "node_memory_MemTotal_bytes{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "total",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "buffered",
     "expr": "node_memory_Cached_bytes{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cached",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    },
    {
     "alias": "cached",
     "expr": "node_memory_Buffers_bytes{instance=~\"$router$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$router$\"}-node_memory_MemFree_bytes{instance=~\"$router$\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}
{
 "title": "Hardware",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wrk-master",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.30:9100\"})"
    }
   ]
  },
  {
   "title": "wrk-1",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.31:9100\"})"
    }
   ]
  },
  {
   "title": "wrk-2",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.32:9100\"})"
    }
   ]
  },
  {
   "title": "wrk-3",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.33:9100\"})"
    }
   ]
  },
  {
   "title": "wrk-4",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.34:9100\"})"
    }
   ]
  },
  {
   "title": "Core Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}
{
 "title": "Weather Stations",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": "label_values(weather_station_snow_hight,site)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_air_temperature{site='$site'}"
    }
   ]
  },
  {
   "title": "Current Snow Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "lengthm",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_snow_hight{site=\"$site\"}/100"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_air_humidity{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "velocitykmh",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_speed{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Gusts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "velocitykmh",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_gust_speed{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Current Wind Direction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "expr": "weather_station_wind_direction{site=\"$site\"}"
    }
   ]
  },
  {
   "title": "Air Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "weather_station_air_humidity", "legendFormat": "{{ site }}" }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "weather_station_air_temperature",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Snow hight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "weather_station_snow_hight / 100",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Surface Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "weather_station_surface_temperature",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Wind Speeds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    { "expr": "weather_station_wind_speed", "legendFormat": "{{ site }}" },
    {
     "expr": "weather_station_wind_gust_speed",
     "legendFormat": "{{ site }} - gusts"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    { "expr": "weather_station_wind_direction", "legendFormat": "{{ site }}" }
   ]
  }
 ]
}
{
 "title": "mosquitto-exporter",
 "description": "Simple dashboard for https://github.com/sapcc/mosquitto-exporter",
 "tags": [
  "mqtt",
  "mosquitto",
  "iot"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(broker_uptime, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(broker_bytes_received[5m])",
     "legendFormat": "bytes_received"
    },
    { "expr": "-rate(broker_bytes_sent[5m])", "legendFormat": "bytes_sent" }
   ]
  },
  {
   "title": "clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "clients_connected" },
    { "expr": "-broker_clients_disconnected", "legendFormat": "clients_disconnected" },
    { "expr": "broker_clients_expired", "legendFormat": "clients_expired" },
    { "expr": "broker_clients_maximum", "legendFormat": "clients_maximum" },
    { "expr": "broker_clients_total", "legendFormat": "clients_total" }
   ]
  },
  {
   "title": "publish/messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_dropped[5m])",
     "legendFormat": "publish_messages_dropped"
    },
    {
     "expr": "rate(broker_publish_messages_received[5m])",
     "legendFormat": "publish_messages_received"
    },
    {
     "expr": "-rate(broker_publish_messages_sent[5m])",
     "legendFormat": "publish_messages_sent"
    }
   ]
  },
  {
   "title": "publish/traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_bytes_received[5m])",
     "legendFormat": "publish_bytes_received"
    },
    {
     "expr": "-rate(broker_publish_bytes_sent[5m])",
     "legendFormat": "publish_bytes_sent"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "broker_uptime", "legendFormat": "uptime" }
   ]
  },
  {
   "title": "subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_shared_subscriptions_count",
     "legendFormat": "shared_subscriptions_count"
    },
    { "expr": "broker_subscriptions_count", "legendFormat": "subscriptions_count" }
   ]
  },
  {
   "title": "messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_messages_received[5m])",
     "legendFormat": "messages_received"
    },
    {
     "expr": "-rate(broker_messages_sent[5m])",
     "legendFormat": "messages_sent"
    }
   ]
  },
  {
   "title": "stored messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "broker_store_messages_bytes", "legendFormat": "store_messages_bytes" },
    { "expr": "broker_messages_stored", "legendFormat": "messages_stored" }
   ]
  },
  {
   "title": "retained messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_retained_messages_count", "legendFormat": "retained_messages_count" }
   ]
  },
  {
   "title": "load/traffics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "broker_load_bytes_received_15min",
     "legendFormat": "load_bytes_received_15min"
    },
    {
     "expr": "broker_load_bytes_received_5min",
     "legendFormat": "load_bytes_received_5min"
    },
    {
     "expr": "broker_load_bytes_received_1min",
     "legendFormat": "load_bytes_received_1min"
    },
    { "expr": "-broker_load_bytes_sent_15min", "legendFormat": "load_bytes_sent_15min" },
    { "expr": "-broker_load_bytes_sent_5min", "legendFormat": "load_bytes_sent_5min" },
    { "expr": "-broker_load_bytes_sent_1min", "legendFormat": "load_bytes_sent_1min" }
   ]
  },
  {
   "title": "load/connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_load_connections_15min", "legendFormat": "load_connections_15min" },
    { "expr": "broker_load_connections_5min", "legendFormat": "load_connections_5min" },
    { "expr": "broker_load_connections_1min", "legendFormat": "load_connections_1min" }
   ]
  },
  {
   "title": "load/messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_load_messages_received_15min",
     "legendFormat": "load_messages_received_15min"
    },
    {
     "expr": "broker_load_messages_received_5min",
     "legendFormat": "load_messages_received_5min"
    },
    {
     "expr": "broker_load_messages_received_1min",
     "legendFormat": "load_messages_received_1min"
    },
    {
     "expr": "-broker_load_messages_sent_15min",
     "legendFormat": "load_messages_sent_15min"
    },
    {
     "expr": "-broker_load_messages_sent_5min",
     "legendFormat": "load_messages_sent_5min"
    },
    {
     "expr": "-broker_load_messages_sent_1min",
     "legendFormat": "load_messages_sent_1min"
    }
   ]
  },
  {
   "title": "load/publish",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_load_publish_dropped_15min",
     "legendFormat": "load_publish_dropped_15min"
    },
    {
     "expr": "broker_load_publish_dropped_5min",
     "legendFormat": "load_publish_dropped_5min"
    },
    {
     "expr": "broker_load_publish_dropped_1min",
     "legendFormat": "load_publish_dropped_1min"
    },
    {
     "expr": "broker_load_publish_received_15min",
     "legendFormat": "load_publish_received_15min"
    },
    {
     "expr": "broker_load_publish_received_5min",
     "legendFormat": "load_publish_received_5min"
    },
    {
     "expr": "broker_load_publish_received_1min",
     "legendFormat": "load_publish_received_1min"
    },
    {
     "expr": "-broker_load_publish_sent_15min",
     "legendFormat": "load_publish_sent_15min"
    },
    { "expr": "-broker_load_publish_sent_5min", "legendFormat": "load_publish_sent_5min" },
    { "expr": "-broker_load_publish_sent_1min", "legendFormat": "load_publish_sent_1min" }
   ]
  },
  {
   "title": "load/sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_load_sockets_15min", "legendFormat": "load_sockets_15min" },
    { "expr": "broker_load_sockets_5min", "legendFormat": "load_sockets_5min" },
    { "expr": "broker_load_sockets_1min", "legendFormat": "load_sockets_1min" }
   ]
  }
 ]
}