apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: grafana
        image: carlosedp/monitoring-grafana:v5.1.3
        volumeMounts:
        - name: grafana-config
          mountPath: /grafana/conf/config.ini
          subPath: config.ini
        - name: grafana-claim
          mountPath: /data
        - name: grafana-datasources
          mountPath: /grafana/conf/provisioning/datasources
        ports:
        - name: web
          containerPort: 3000
        env:
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource"
        - name: GF_PATHS_PLUGINS
          value: "/data/plugins"
        resources:
          requests:
            memory: 180Mi
            cpu: 100m
          limits:
            memory: 180Mi
            cpu: 200m
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
  volumeClaimTemplates:
  - metadata:
      name: grafana-claim
    spec:
      storageClassName: managed-nfs-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
