apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        k3s.io/hostname: wrk-2
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: grafana
        image: grafana/grafana:latest
        volumeMounts:
        - name: grafana-claim
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /grafana/provisioning/datasources
        ports:
        - name: web
          containerPort: 3000
        env:
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource"
        - name: GF_PATHS_PROVISIONING
          value: "/grafana/provisioning/datasources"
        resources:
          requests:
            memory: 180Mi
            cpu: 100m
          limits:
            memory: 180Mi
            cpu: 200m
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-claim
        persistentVolumeClaim:
          claimName: grafana
