{
 "title": "Blackbox Exporter ICMP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targets",
    "label": "targets",
    "query": {
     "query": "label_values(probe_success{job=\"internet_latency\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ICMP $targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=~\"$targets\"}",
     "legendFormat": "{{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$targets\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RTT duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{instance=~\"$targets\",phase=\"rtt\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}