{
 "title": "ZHA temperature sensors",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "sensor",
    "query": {
     "query": "label_values(hass_sensor_temperature_celsius,friendly_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hass_sensor_battery_percent{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}