{
 "title": "ZHA temperature sensors",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "sensor",
    "query": {
     "query": "label_values(hass_sensor_temperature_celsius,friendly_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_battery_percent{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}
{
 "title": "ZHA Power sensors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "sensor",
    "query": {
     "query": "label_values(hass_sensor_power_w,friendly_name)"
    }
   },
   { "name": "cost", "query": "0.1304, 0.16" },
   {
    "name": "time",
    "query": "1h,6h,12h,1d,7d,14d,30d,60d,90d,180d,365d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cost Over Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(hass_sensor_energy_kwh{}[$time]))*$cost"
    }
   ]
  },
  {
   "title": "Power usage [kwh] 15m rolling",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((sum_over_time(hass_sensor_power_w{}[1h])/count_over_time(hass_sensor_power_w{}[1h])/1000)[1h:15m]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "sum_over_time((sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)[1h:15m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power usage [kwh] 15m rolling",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((sum_over_time(hass_sensor_power_w{}[1h])/count_over_time(hass_sensor_power_w{}[1h])/1000)[1h:15m]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "sum_over_time((sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)[1h:15m])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Current usage [A]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "amp", "label": "amps" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_current_a{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Total Energie Over Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(hass_sensor_power_w{}[$time])/count_over_time(hass_sensor_power_w{}[1h])/1000)"
    }
   ]
  },
  {
   "title": "Power usage [kwh] 24h rolling",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((sum_over_time(hass_sensor_power_w{}[1h])/count_over_time(hass_sensor_power_w{}[1h])/1000)[1w:1d]))",
     "legendFormat": "SUM"
    },
    {
     "expr": "sum_over_time((sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)[1w:1d])",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power usage [w]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_power_w{friendly_name=~\"$sensor.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power consumption per time",
   "type": "table",
   "description": "based on  current consumption",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[$time])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Cost per time",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[$time])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)*$cost",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Yearly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power consumption per year [kwh]",
   "type": "table",
   "description": "based on last 30 days",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[30d])/count_over_time(hass_sensor_power_w{friendly_name=~\"$sensor.*\"}[1h])/1000)*12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power consumption per year [%]",
   "type": "table",
   "description": "based on last 30 days",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(hass_sensor_power_w{}[30d])/count_over_time(hass_sensor_power_w{}[1h])/1000*12 / ignoring(domain,entity,friendly_name,instance,job) group_left sum(sum_over_time(hass_sensor_power_w{}[30d])/count_over_time(hass_sensor_power_w{}[1h])/1000*12) *100) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}