{
 "title": "mosquitto-exporter",
 "description": "Simple dashboard for https://github.com/sapcc/mosquitto-exporter",
 "tags": [
  "mqtt",
  "mosquitto",
  "iot"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(broker_uptime, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(broker_bytes_received[5m])",
     "legendFormat": "bytes_received"
    },
    { "expr": "-rate(broker_bytes_sent[5m])", "legendFormat": "bytes_sent" }
   ]
  },
  {
   "title": "clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "clients_connected" },
    { "expr": "-broker_clients_disconnected", "legendFormat": "clients_disconnected" },
    { "expr": "broker_clients_expired", "legendFormat": "clients_expired" },
    { "expr": "broker_clients_maximum", "legendFormat": "clients_maximum" },
    { "expr": "broker_clients_total", "legendFormat": "clients_total" }
   ]
  },
  {
   "title": "publish/messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_dropped[5m])",
     "legendFormat": "publish_messages_dropped"
    },
    {
     "expr": "rate(broker_publish_messages_received[5m])",
     "legendFormat": "publish_messages_received"
    },
    {
     "expr": "-rate(broker_publish_messages_sent[5m])",
     "legendFormat": "publish_messages_sent"
    }
   ]
  },
  {
   "title": "publish/traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_publish_bytes_received[5m])",
     "legendFormat": "publish_bytes_received"
    },
    {
     "expr": "-rate(broker_publish_bytes_sent[5m])",
     "legendFormat": "publish_bytes_sent"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "broker_uptime", "legendFormat": "uptime" }
   ]
  },
  {
   "title": "subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_shared_subscriptions_count",
     "legendFormat": "shared_subscriptions_count"
    },
    { "expr": "broker_subscriptions_count", "legendFormat": "subscriptions_count" }
   ]
  },
  {
   "title": "messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(broker_messages_received[5m])",
     "legendFormat": "messages_received"
    },
    {
     "expr": "-rate(broker_messages_sent[5m])",
     "legendFormat": "messages_sent"
    }
   ]
  },
  {
   "title": "stored messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "broker_store_messages_bytes", "legendFormat": "store_messages_bytes" },
    { "expr": "broker_messages_stored", "legendFormat": "messages_stored" }
   ]
  },
  {
   "title": "retained messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_retained_messages_count", "legendFormat": "retained_messages_count" }
   ]
  },
  {
   "title": "load/traffics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "broker_load_bytes_received_15min",
     "legendFormat": "load_bytes_received_15min"
    },
    {
     "expr": "broker_load_bytes_received_5min",
     "legendFormat": "load_bytes_received_5min"
    },
    {
     "expr": "broker_load_bytes_received_1min",
     "legendFormat": "load_bytes_received_1min"
    },
    { "expr": "-broker_load_bytes_sent_15min", "legendFormat": "load_bytes_sent_15min" },
    { "expr": "-broker_load_bytes_sent_5min", "legendFormat": "load_bytes_sent_5min" },
    { "expr": "-broker_load_bytes_sent_1min", "legendFormat": "load_bytes_sent_1min" }
   ]
  },
  {
   "title": "load/connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_load_connections_15min", "legendFormat": "load_connections_15min" },
    { "expr": "broker_load_connections_5min", "legendFormat": "load_connections_5min" },
    { "expr": "broker_load_connections_1min", "legendFormat": "load_connections_1min" }
   ]
  },
  {
   "title": "load/messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_load_messages_received_15min",
     "legendFormat": "load_messages_received_15min"
    },
    {
     "expr": "broker_load_messages_received_5min",
     "legendFormat": "load_messages_received_5min"
    },
    {
     "expr": "broker_load_messages_received_1min",
     "legendFormat": "load_messages_received_1min"
    },
    {
     "expr": "-broker_load_messages_sent_15min",
     "legendFormat": "load_messages_sent_15min"
    },
    {
     "expr": "-broker_load_messages_sent_5min",
     "legendFormat": "load_messages_sent_5min"
    },
    {
     "expr": "-broker_load_messages_sent_1min",
     "legendFormat": "load_messages_sent_1min"
    }
   ]
  },
  {
   "title": "load/publish",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "broker_load_publish_dropped_15min",
     "legendFormat": "load_publish_dropped_15min"
    },
    {
     "expr": "broker_load_publish_dropped_5min",
     "legendFormat": "load_publish_dropped_5min"
    },
    {
     "expr": "broker_load_publish_dropped_1min",
     "legendFormat": "load_publish_dropped_1min"
    },
    {
     "expr": "broker_load_publish_received_15min",
     "legendFormat": "load_publish_received_15min"
    },
    {
     "expr": "broker_load_publish_received_5min",
     "legendFormat": "load_publish_received_5min"
    },
    {
     "expr": "broker_load_publish_received_1min",
     "legendFormat": "load_publish_received_1min"
    },
    {
     "expr": "-broker_load_publish_sent_15min",
     "legendFormat": "load_publish_sent_15min"
    },
    { "expr": "-broker_load_publish_sent_5min", "legendFormat": "load_publish_sent_5min" },
    { "expr": "-broker_load_publish_sent_1min", "legendFormat": "load_publish_sent_1min" }
   ]
  },
  {
   "title": "load/sockets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "broker_load_sockets_15min", "legendFormat": "load_sockets_15min" },
    { "expr": "broker_load_sockets_5min", "legendFormat": "load_sockets_5min" },
    { "expr": "broker_load_sockets_1min", "legendFormat": "load_sockets_1min" }
   ]
  }
 ]
}