---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmapwatching-role
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmapwatching
  namespace: monitoring
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: configmapwatching-rolebind
roleRef:
  kind: ClusterRole
  name: configmapwatching-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: configmapwatching
  namespace: monitoring
