{
 "title": "Grafana",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(grafana_info,kubernetes_name)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(grafana_info,version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{kubernetes_name=\"$pod\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "singlestat",
   "description": "total amount of orgs",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{kubernetes_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "singlestat",
   "description": "total amount of users",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "grafana_stat_total_users{kubernetes_name=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    { "expr": "topk(1, grafana_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "singlestat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(grafana_alerting_active_alerts[1m])"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{kubernetes_name=\"$pod\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_name=\"$pod\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Response Statuses",
   "type": "graph",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp Details",
   "type": "graph",
   "description": "http request counter",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "graph",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_login_post_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{kubernetes_name=\"$pod\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "graph",
   "description": "summary for dataproxy request duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Avg [5 min]",
   "type": "graph",
   "description": "average dataproxy request duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "Average Requests Duration"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{kubernetes_name=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{kubernetes_name=\"$pod\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{kubernetes_name=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}