apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  config.ini: |
    [database]
    path = /data/grafana.db

    [paths]
    data = /data
    logs = /data/log
    plugins = /data/plugins

    [session]
    provider = memory

    [auth.basic]
    enabled = false

    [auth.anonymous]
    enabled = false

    [smtp]
    enabled = true
    host = smtp-server.monitoring.svc:25 
    user =
    password =
    from_address = 'carlosedp@gmail.com'
    from_name = Grafana Alert
    skip_verify = true
