apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |+
    datasources:
     - name: prometheus
       type: prometheus
       access: proxy
       org_id: 1
       url: http://prometheus.monitoring.svc:9090
       version: 1
       editable: false
     - name: prometheus-backup
       type: prometheus
       access: proxy
       org_id: 1
       url: http://prometheus-backup.monitoring.svc:9090
       version: 1
       editable: false
