apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: configmapwatching
      securityContext:
        fsGroup: 65534
        runAsNonRoot: false
        runAsUser: 65534
      containers:
      - name: sidecar
        image: kiwigrid/k8s-sidecar:latest
        volumeMounts:
        - name: grafana-dashboards
          mountPath: /tmp/
        env:
        - name: LABEL
          value: "grafana-dashboard"
        - name: FOLDER
          value: /tmp/
        - name: FOLDER_ANNOTATION
          value: "grafana-dashboard-folder"
      - name: grafana
        image: grafana/grafana:7.4.3
        volumeMounts:
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-datasources
          mountPath: /grafana/provisioning/datasources
        - name: grafana-dashboard
          mountPath: /grafana/provisioning/dashboards
        ports:
        - name: web
          containerPort: 3000
        env:
        - name: GF_SERVER_ROOT_URL
          value: https://tevnan.duckdns.org/grafana
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource"
        - name: GF_PATHS_PROVISIONING
          value: "/grafana/provisioning/"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-password
        resources:
          requests:
            memory: 180Mi
            cpu: 100m
          limits:
            memory: 180Mi
            cpu: 200m
      volumes:
      - name: grafana-dashboards
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard
        configMap:
          name: grafana-dashboard
