---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flexget
  namespace: flexget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
