---
apiVersion: v1
kind: Service
metadata:
  name: mktxp-monitoring
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '49090'
  labels:
    longterm: 'true'
spec:
  selector:
    app: mktxp-exporter
  ports:
  - port: 49090
    targetPort: 49090
