apiVersion: v1
kind: Service
metadata:
  name: prometheus-backup-external
  namespace: monitoring
  
spec:
  selector: 
    k8s-app: prometheus-backup
  type: NodePort  
  ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 30003
