---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-backup
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
