apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-backup-config
  namespace: monitoring
  labels:
    name: prometheus-backup-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 80s
      scrape_timeout: 60s
      evaluation_interval: 75s
    rule_files:
      - /etc/config/*.rules
    alerting:
      alertmanagers:
      - scheme: http
        path_prefix: "alertmanager/"
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus.monitoring.svc:9090']
    - job_name: 'prometheus-backup'
      static_configs:
        - targets: ['prometheus-backup.monitoring.svc:9090']
    - job_name: 'federate'
  
      honor_labels: true
      metrics_path: '/federate'
  
      params:
        'match[]':
          - '{longterm="true"}'
      static_configs:
        - targets:
          - 'prometheus:9090'
