{
 "title": "Kubernetes cluster monitoring",
 "description": "Monitor a Kubernetes cluster using Prometheus TSDB.  Shows overall cluster CPU / Memory / Disk usage as well as individual pod statistics. ",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (io_kubernetes_container_name)( rate(container_cpu_usage_seconds_total{image!=\"\"}[2m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=\"/\"}) - sum(node_filesystem_free_bytes{mountpoint=\"/\"}) ) / sum(node_filesystem_size_bytes{mountpoint=\"/\"})*100"
    }
   ]
  },
  {
   "title": "Cluster Data Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=~\"/var/lib/heketi/mounts.*\"}) - sum(node_filesystem_free_bytes{mountpoint=~\"/var/lib/heketi/mounts.*\"}) ) / sum(node_filesystem_size_bytes{mountpoint=~\"/var/lib/heketi/mounts.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name, namespace, kubernetes_io_hostname )( rate(container_cpu_usage_seconds_total{image!=\"\",pod_name!=\"\"}[2m] ) )",
     "legendFormat": "{{kubernetes_io_hostname}} -{{ pod_name }}-({{ namespace }})"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",name!=\"\"}) by (name, namespace, kubernetes_io_hostname))",
     "legendFormat": "{{kubernetes_io_hostname}} -{{ pod_name }}-({{ namespace }})"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name, namespace,kubernetes_io_hostname) (rate (container_network_receive_bytes_total{name!=\"\",name!=\"\"}[2m]) ))",
     "legendFormat": "{{kubernetes_io_hostname}} -{{ pod_name }}-({{ namespace }})"
    },
    {
     "expr": "sort_desc(sum by (pod_name, namespace,kubernetes_io_hostname) (rate (container_network_transmit_bytes_total{name!=\"\",name!=\"\"}[2m]) ))",
     "legendFormat": "{{kubernetes_io_hostname}} -{{ pod_name }}-({{ namespace }})"
    }
   ]
  }
 ]
}