{
 "title": "Router",
 "description": "Host overview tuned to router specs",
 "tags": [
  "system",
  "os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Contract Table",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{job=\"router\"}/node_nf_conntrack_entries_limit {job=\"router\"}*100"
    }
   ]
  },
  {
   "title": "Router CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{job=\"router\",mode!=\"idle\"})/sum(node_cpu_seconds_total{job=\"router\"})*100"
    }
   ]
  },
  {
   "title": "Router Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes{job=\"router\"}-node_memory_MemFree_bytes{job=\"router\"}-node_memory_Cached_bytes{job=\"router\"})/(node_memory_MemTotal_bytes{job=\"router\"})) by (job) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"router\"}[2m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic (br-wan)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "received",
     "expr": "irate(node_network_transmit_bytes_total{job=\"router\"}[2m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "br-wan" }
     ]
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "alias": "used",
     "expr": "sum((node_memory_MemTotal_bytes{job=\"router\"}-node_memory_MemFree_bytes{job=\"router\"}-node_memory_Cached_bytes{job=\"router\"})/(node_memory_MemTotal_bytes{job=\"router\"})) by (job) * 100",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "%",
     "measurement": "memory_value",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"host\" =~ /^$host$/ AND \"type_instance\" = 'used' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "short",
     "expr": "node_load1{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "short",
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "medium",
     "expr": "node_load5{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "mid",
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "long",
     "expr": "node_load15{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "long",
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors/Drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{job=\"router\"}[2m])",
     "legendFormat": "{{device}} drops"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"router\"}[2m])",
     "legendFormat": "{{device}} error"
    }
   ]
  },
  {
   "title": "Memory Distrubution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "free",
     "expr": "node_memory_MemTotal_bytes{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "total",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "buffered",
     "expr": "node_memory_Cached_bytes{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "cached",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ]
    },
    {
     "alias": "cached",
     "expr": "node_memory_Buffers_bytes{job=\"router\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers",
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    }
   ]
  }
 ]
}