---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dlan-exporter
    k8s-app: dlan-exporter
    location: upstairs
  name: dlan-exporter-upstairs
  namespace: monitoring
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
  labels:
    app: dlan-exporter
    k8s-app: dlan-exporter
  name: dlan-exporter-upstairs
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.1.5
  ports:
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dlan-exporter
    k8s-app: dlan-exporter
    location: downstairs
  name: dlan-exporter-downstairs
  namespace: monitoring
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
  labels:
    app: dlan-exporter
    k8s-app: dlan-exporter
  name: dlan-exporter-downstairs
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.1.33
  ports:
  - name: http
    port: 8080
    protocol: TCP

