apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus.tevnan.io
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
