apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    longterm: 'true'
  name: blackbox-exporter
  namespace: monitoring
spec:
  selector: 
    app: blackbox-exporter 
  ports:
    - port: 9115
      targetPort: 9115
