---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-monitoring
  namespace: mosquitto
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    longterm: 'true'
spec:
  selector:
    app: mosquitto
  ports:
  - port: 9234
    targetPort: 9234
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31883

